AWSTemplateFormatVersion: 2010-09-09

# Stand up an ECS cluster.      

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: "Network Configuration"
        Parameters: 
          - VpcId
          - SubnetIds
      - Label: 
          default: "ECS Cluster"
        Parameters: 
          - InstanceType
          - MaxSize
          - DesiredCapacity

Parameters:
  
  MaxSize:
    Type: String
    Default: 1
    Description: Maximum number of ECS instances.

  DesiredCapacity:
    Type: String
    Default: 1
    Description: Desired number of ECS instances.

  InstanceType:
    Type: String
    AllowedValues: 
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - t2.xlarge 
    Default: t2.micro
    Description: What kind of instance types in the cluster?

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select a VPC that allows instances access to the Internet.

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select 1-2 subnets in your selected VPC, private preferred if NATting is setup.  ECS cluster nodes will run here.

  ECSAMI:
    Type:  AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id
  #  Default: /aws/service/ecs/optimized-ami/amazon-linux/recommended/image_id
    Description: You probably won't need to change this value.  This is looking up the latest Amazon Linux 2 AMI for ECS using the Parameter Store...



Resources:

  # The IAM Role to be used by the EC2 instances in the ECS cluster.
  # Allows your Amazon ECS container agent to register / deregister with load balancer. 
  ECSContainerAgentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-ECSContainerAgentRole
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: ecs.amazonaws.com
      Policies:
      - PolicyName:  !Sub ${AWS::StackName}-ECSContainerAgentPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: 
              - elasticloadbalancing:Register*
              - elasticloadbalancing:Deregister*
              - elasticloadbalancing:Describe*
              - ec2:Describe*
              - ec2:AuthorizeSecurityGroupIngress
            Resource: '*'

  AutoscalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-ClusterAutoscalingRole
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: application-autoscaling.amazonaws.com
      Path: /
      Policies:
      - PolicyName: !Sub ${AWS::StackName}-ClusterAutoscalingPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: 
              - application-autoscaling:*
              - cloudwatch:DescribeAlarms
              - cloudwatch:PutMetricAlarm
              - ecs:DescribeServices
              - ecs:UpdateService
            Resource: '*'

  # Permissions associated with each ECS Instance.
  ECSInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-ECSInstanceRole
      ManagedPolicyArns: [ "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role" ]
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: ec2.amazonaws.com


  # Now, an ECS Cluster to deploy to:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${AWS::StackName}-ECSCluster    # Something you can recognize in the console, but unique.


  # Security Group for the ECS instances.  Allow inbound ports for the ELB to use:
  EcsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${AWS::StackName}-EcsSecurityGroup
      GroupDescription: ECS Security Group
      VpcId: !Ref VpcId

  #  Inbound rules for HTTP on 80.  31000 - 61000 is for dynamic port assignment in ECS:
  EcsSecurityGroupHTTPinbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EcsSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0     # This is pretty wide open.  In a real cluster I might restrict the source to a known SG used by the LB
  EcsSecurityGroupALBports:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EcsSecurityGroup
      IpProtocol: tcp
      FromPort: 31000
      ToPort: 61000
      CidrIp: 0.0.0.0/0     # This is pretty wide open.  In a real cluster I might restrict the source to a known SG used by the LB

  # Auto-Scaling Group for the cluser:
  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref SubnetIds
      LaunchConfigurationName: !Ref ContainerInstances
      MinSize: 1
      MaxSize: !Ref MaxSize
      DesiredCapacity: !Ref DesiredCapacity
      Tags:
      - Key: Name
        Value: ECS Cluster Node
        PropagateAtLaunch: true
      - Key: MemberOfCluster
        Value: !Ref ECSCluster
        PropagateAtLaunch: true
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M     
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: true

  # The LaunchConfiguration for the cluster:      
  ContainerInstances:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref ECSAMI
      # ImageId: !FindInMap [AmazonLinuxAMI, !Ref 'AWS::Region', AMI]
      SecurityGroups: [!Ref EcsSecurityGroup]
      InstanceType: !Ref InstanceType 
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          # Critical: this ecs.config file must know the name of the cluster to connect to.
          # This is the only actual setup required (besides the pre-installed software)
          echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
          yum update -y
          # These appear to be installed already
          yum install -y aws-cfn-bootstrap awslogs 
          
          # Believe it or not, you have to configure CloudWatch Logs yourself:
          # Inject the CloudWatch Logs configuration file contents
          cat > /etc/awslogs/awslogs.conf <<EOF
          [general]
          state_file = /var/lib/awslogs/agent-state        

          [/var/log/dmesg]
          file = /var/log/dmesg
          log_group_name = {cluster}/var/log/dmesg
          log_stream_name = {cluster}

          [/var/log/messages]
          file = /var/log/messages
          log_group_name = {cluster}/var/log/messages
          log_stream_name = {cluster}
          datetime_format = %b %d %H:%M:%S

          [/var/log/docker]
          file = /var/log/docker
          log_group_name = {cluster}/var/log/docker
          log_stream_name = {cluster}
          datetime_format = %Y-%m-%dT%H:%M:%S.%f

          [/var/log/ecs/ecs-init.log]
          file = /var/log/ecs/ecs-init.log
          log_group_name = {cluster}/var/log/ecs/ecs-init.log
          log_stream_name = {cluster}
          datetime_format = %Y-%m-%dT%H:%M:%SZ

          [/var/log/ecs/ecs-agent.log]
          file = /var/log/ecs/ecs-agent.log.*
          log_group_name = {cluster}/var/log/ecs/ecs-agent.log
          log_stream_name = {cluster}
          datetime_format = %Y-%m-%dT%H:%M:%SZ

          [/var/log/ecs/audit.log]
          file = /var/log/ecs/audit.log.*
          log_group_name = {cluster}/var/log/ecs/audit.log
          log_stream_name = {cluster}
          datetime_format = %Y-%m-%dT%H:%M:%SZ
          EOF
          # Replace 
          sed -i -e "s/{cluster}/${ECSCluster}/g" /etc/awslogs/awslogs.conf
          # Start CloudWatch logs service:
          systemctl start awslogsd
          # Make sure CloudWatch logs starts on restart:
          systemctl enable awslogsd.service
          # Signal CloudFormation we are complete:
          /opt/aws/bin/cfn-signal --resource ECSAutoScalingGroup --stack ${AWS::StackName} --region ${AWS::Region}


  # Attach EC2Role's permissions to each ECS Instance.
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [!Ref ECSInstanceRole]

  # This LogsGroup will be useful when several containers emit output:
  CloudwatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${AWS::StackName}-ECSLogGroup
      RetentionInDays: 3


Outputs:
  ecscluster:
    Value: !Ref ECSCluster
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", ECSCluster ] ]
